### ISSUE TITLE
Creating Issue Test 1

### ISSUE THREAD

**Issue by chaoxng** [chaoxng/github-trello-issue-tracker#8]
With description of course

updating this doesn't work once the issue is closed

repoened?

**Comment by chaoxng** [comment]
[Issue](https://trello.com/c/DKaG3Fqm) created by [@feliciousx](https://trello.com/feliciousx)

**Comment by FeliciousX** [comment]
it's done

**Comment by chaoxng** [comment]
[Issue](https://trello.com/c/DKaG3Fqm) closed by [@chaong](https://trello.com/chaong)
